//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reseller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buyer()
        {
            this.ResellerOrder = new HashSet<ResellerOrder>();
        }
    
        public int BuyerID { get; set; }
        public string BuyerUserName { get; set; }
        public string BuyerName { get; set; }
        public string PhoneBuyer { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual RoleUsers RoleUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResellerOrder> ResellerOrder { get; set; }
    }
}
