//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reseller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResellerOrder
    {
        public int OrderNo { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> EstateID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Buyer Buyer { get; set; }
        public virtual Estate Estate { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
