//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reseller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ResellerOrder = new HashSet<ResellerOrder>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleName { get; set; }
        public string BrandName { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleModelName { get; set; }
        public string VehicleSituation { get; set; }
        public string FuelType { get; set; }
        public string VehiclePrice { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> VCategoryID { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResellerOrder> ResellerOrder { get; set; }
        public virtual Status Status { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
    }
}
